### ISSUE TITLE
sp and dp not displayed

### ISSUE THREAD

**Issue by art0** [mbolli/nfsen-ng#49] opened 2020-05-26 13:57 UTC
How to reproduce

- Nfdump returns a full CSV with the source and destination  port of the flows
- I select any format that contains %dp 
Ports are not displayed in the GUI

Get CSV: returns the CSV with those fields

**Comment by mbolli** [comment] 2020-05-26 14:07
Duplicate of #48

**Closed by mbolli** 2020-05-26 14:07 UTC

**Comment by art0** [comment] 2020-05-26 14:19
What is the syntax for the Custom $format in the GUI?
Thanks for quick response

**Comment by mbolli** [comment] 2020-05-26 15:44
@art0 this didn't work until now. I just fixed it. You can use the nfdump formats as specified in the docs, e.g. https://manpages.ubuntu.com/manpages/xenial/man1/nfdump.1.html#output%20formats
